server:
  port: 8081
Spring:  
  cloud: 
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/juangarcia204/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service          
      
    
